import atom

def main():
    # Periodic Table - neutrons based on most abundant/stable isotope
    hydrogen      = atom("Hydrogen",       "H",   1,   1,   0)
    helium        = atom("Helium",         "He",  2,   2,   2)
    lithium       = atom("Lithium",        "Li",  3,   3,   4)
    beryllium     = atom("Beryllium",      "Be",  4,   4,   5)
    boron         = atom("Boron",          "B",   5,   5,   6)
    carbon        = atom("Carbon",         "C",   6,   6,   6)
    nitrogen      = atom("Nitrogen",       "N",   7,   7,   7)
    oxygen        = atom("Oxygen",         "O",   8,   8,   8)
    fluorine      = atom("Fluorine",       "F",   9,   9,  10)
    neon          = atom("Neon",           "Ne", 10,  10,  10)
    sodium        = atom("Sodium",         "Na", 11,  11,  12)
    magnesium     = atom("Magnesium",      "Mg", 12,  12,  12)
    aluminum      = atom("Aluminum",       "Al", 13,  13,  14)
    silicon       = atom("Silicon",        "Si", 14,  14,  14)
    phosphorus    = atom("Phosphorus",     "P",  15,  15,  16)
    sulfur        = atom("Sulfur",         "S",  16,  16,  16)
    chlorine      = atom("Chlorine",       "Cl", 17,  17,  18)
    argon         = atom("Argon",          "Ar", 18,  18,  22)
    potassium     = atom("Potassium",      "K",  19,  19,  20)
    calcium       = atom("Calcium",        "Ca", 20,  20,  20)
    scandium      = atom("Scandium",       "Sc", 21,  21,  24)
    titanium      = atom("Titanium",       "Ti", 22,  22,  26)
    vanadium      = atom("Vanadium",       "V",  23,  23,  28)
    chromium      = atom("Chromium",       "Cr", 24,  24,  28)
    manganese     = atom("Manganese",      "Mn", 25,  25,  30)
    iron          = atom("Iron",           "Fe", 26,  26,  30)
    cobalt        = atom("Cobalt",         "Co", 27,  27,  32)
    nickel        = atom("Nickel",         "Ni", 28,  28,  30)
    copper        = atom("Copper",         "Cu", 29,  29,  34)
    zinc          = atom("Zinc",           "Zn", 30,  30,  34)
    gallium       = atom("Gallium",        "Ga", 31,  31,  38)
    germanium     = atom("Germanium",      "Ge", 32,  32,  42)
    arsenic       = atom("Arsenic",        "As", 33,  33,  42)
    selenium      = atom("Selenium",       "Se", 34,  34,  46)
    bromine       = atom("Bromine",        "Br", 35,  35,  44)
    krypton       = atom("Krypton",        "Kr", 36,  36,  48)
    rubidium      = atom("Rubidium",       "Rb", 37,  37,  48)
    strontium     = atom("Strontium",      "Sr", 38,  38,  50)
    yttrium       = atom("Yttrium",        "Y",  39,  39,  50)
    zirconium     = atom("Zirconium",      "Zr", 40,  40,  50)
    niobium       = atom("Niobium",        "Nb", 41,  41,  52)
    molybdenum    = atom("Molybdenum",     "Mo", 42,  42,  56)
    technetium    = atom("Technetium",     "Tc", 43,  43,  55)
    ruthenium     = atom("Ruthenium",      "Ru", 44,  44,  58)
    rhodium       = atom("Rhodium",        "Rh", 45,  45,  58)
    palladium     = atom("Palladium",      "Pd", 46,  46,  60)
    silver        = atom("Silver",         "Ag", 47,  47,  60)
    cadmium       = atom("Cadmium",        "Cd", 48,  48,  66)
    indium        = atom("Indium",         "In", 49,  49,  66)
    tin           = atom("Tin",            "Sn", 50,  50,  70)
    antimony      = atom("Antimony",       "Sb", 51,  51,  70)
    tellurium     = atom("Tellurium",      "Te", 52,  52,  76)
    iodine        = atom("Iodine",         "I",  53,  53,  74)
    xenon         = atom("Xenon",          "Xe", 54,  54,  78)
    cesium        = atom("Cesium",         "Cs", 55,  55,  78)
    barium        = atom("Barium",         "Ba", 56,  56,  82)
    lanthanum     = atom("Lanthanum",      "La", 57,  57,  82)
    cerium        = atom("Cerium",         "Ce", 58,  58,  82)
    praseodymium  = atom("Praseodymium",   "Pr", 59,  59,  82)
    neodymium     = atom("Neodymium",      "Nd", 60,  60,  84)
    promethium    = atom("Promethium",     "Pm", 61,  61,  84)
    samarium      = atom("Samarium",       "Sm", 62,  62,  90)
    europium      = atom("Europium",       "Eu", 63,  63,  90)
    gadolinium    = atom("Gadolinium",     "Gd", 64,  64,  94)
    terbium       = atom("Terbium",        "Tb", 65,  65,  94)
    dysprosium    = atom("Dysprosium",     "Dy", 66,  66,  98)
    holmium       = atom("Holmium",        "Ho", 67,  67,  98)
    erbium        = atom("Erbium",         "Er", 68,  68,  98)
    thulium       = atom("Thulium",        "Tm", 69,  69, 100)
    ytterbium     = atom("Ytterbium",      "Yb", 70,  70, 104)
    lutetium      = atom("Lutetium",       "Lu", 71,  71, 104)
    hafnium       = atom("Hafnium",        "Hf", 72,  72, 106)
    tantalum      = atom("Tantalum",       "Ta", 73,  73, 108)
    tungsten      = atom("Tungsten",       "W",  74,  74, 110)
    rhenium       = atom("Rhenium",        "Re", 75,  75, 112)
    osmium        = atom("Osmium",         "Os", 76,  76, 116)
    iridium       = atom("Iridium",        "Ir", 77,  77, 116)
    platinum      = atom("Platinum",       "Pt", 78,  78, 117)
    gold          = atom("Gold",           "Au", 79,  79, 118)
    mercury       = atom("Mercury",        "Hg", 80,  80, 122)
    thallium      = atom("Thallium",       "Tl", 81,  81, 124)
    lead          = atom("Lead",           "Pb", 82,  82, 126)
    bismuth       = atom("Bismuth",        "Bi", 83,  83, 126)
    polonium      = atom("Polonium",       "Po", 84,  84, 126)
    astatine      = atom("Astatine",       "At", 85,  85, 125)
    radon         = atom("Radon",          "Rn", 86,  86, 136)
    francium      = atom("Francium",       "Fr", 87,  87, 136)
    radium        = atom("Radium",         "Ra", 88,  88, 138)
    actinium      = atom("Actinium",       "Ac", 89,  89, 138)
    thorium       = atom("Thorium",        "Th", 90,  90, 142)
    protactinium  = atom("Protactinium",   "Pa", 91,  91, 140)
    uranium       = atom("Uranium",        "U",  92,  92, 146)
    neptunium     = atom("Neptunium",      "Np", 93,  93, 144)
    plutonium     = atom("Plutonium",      "Pu", 94,  94, 150)
    americium     = atom("Americium",      "Am", 95,  95, 148)
    curium        = atom("Curium",         "Cm", 96,  96, 151)
    berkelium     = atom("Berkelium",      "Bk", 97,  97, 150)
    californium   = atom("Californium",    "Cf", 98,  98, 153)
    einsteinium   = atom("Einsteinium",    "Es", 99,  99, 153)
    fermium       = atom("Fermium",        "Fm",100, 100, 157)
    mendelevium   = atom("Mendelevium",    "Md",101, 101, 157)
    nobelium      = atom("Nobelium",       "No",102, 102, 157)
    lawrencium    = atom("Lawrencium",     "Lr",103, 103, 159)
    rutherfordium = atom("Rutherfordium",  "Rf",104, 104, 161)
    dubnium       = atom("Dubnium",        "Db",105, 105, 163)
    seaborgium    = atom("Seaborgium",     "Sg",106, 106, 163)
    bohrium       = atom("Bohrium",        "Bh",107, 107, 163)
    hassium       = atom("Hassium",        "Hs",108, 108, 162)
    meitnerium    = atom("Meitnerium",     "Mt",109, 109, 169)
    darmstadtium  = atom("Darmstadtium",   "Ds",110, 110, 171)
    roentgenium   = atom("Roentgenium",    "Rg",111, 111, 170)
    copernicium   = atom("Copernicium",    "Cn",112, 112, 173)
    nihonium      = atom("Nihonium",       "Nh",113, 113, 173)
    flerovium     = atom("Flerovium",      "Fl",114, 114, 175)
    moscovium     = atom("Moscovium",      "Mc",115, 115, 174)
    livermorium   = atom("Livermorium",    "Lv",116, 116, 177)
    tennessine    = atom("Tennessine",     "Ts",117, 117, 177)
    oganesson     = atom("Oganesson",      "Og",118, 118, 176)

    periodic_table = [
        hydrogen, helium, lithium, beryllium, boron, carbon, nitrogen, oxygen,
        fluorine, neon, sodium, magnesium, aluminum, silicon, phosphorus, sulfur,
        chlorine, argon, potassium, calcium, scandium, titanium, vanadium, chromium,
        manganese, iron, cobalt, nickel, copper, zinc, gallium, germanium, arsenic,
        selenium, bromine, krypton, rubidium, strontium, yttrium, zirconium, niobium,
        molybdenum, technetium, ruthenium, rhodium, palladium, silver, cadmium, indium,
        tin, antimony, tellurium, iodine, xenon, cesium, barium, lanthanum, cerium,
        praseodymium, neodymium, promethium, samarium, europium, gadolinium, terbium,
        dysprosium, holmium, erbium, thulium, ytterbium, lutetium, hafnium, tantalum,
        tungsten, rhenium, osmium, iridium, platinum, gold, mercury, thallium, lead,
        bismuth, polonium, astatine, radon, francium, radium, actinium, thorium,
        protactinium, uranium, neptunium, plutonium, americium, curium, berkelium,
        californium, einsteinium, fermium, mendelevium, nobelium, lawrencium,
        rutherfordium, dubnium, seaborgium, bohrium, hassium, meitnerium, darmstadtium,
        roentgenium, copernicium, nihonium, flerovium, moscovium, livermorium,
        tennessine, oganesson,
    ]

main()